zipurl: 'https://s3.waw3-1.cloudferro.com/emodnet/emodnet_seabed_habitats/12549/EUSeaMap_2023.zip'
geodatabase: 'EUSeaMap_2023.gdb'
layer_index: 0
variables:
  - 'EUNIS2019C'
  - 'Energy'
  - 'Substrate'
  - 'Biozone'
resolution: 0.01