name: convertzarrenv
channels:
  - defaults
dependencies:
  - xarray
  - zarr
  - geopandas
  - numpy
  - netcdf4
  - rasterio
  - requests
  - dask
  - tqdm
  - matplotlib
  - cartopy
  - rasterstats
  - ipykernel